# NumPy (Numerical Python)

In [1]:
import numpy as np

# Step 1: Creating and Manipulating Arrays

### Concept:
- A NumPy array is like a supercharged list that can handle math operations on entire datasets at once.
- Think of it as a grid of numbers (like an Excel sheet) optimized for speed.
### Real-World Connection:
Arrays of zeros or ones are used to initialize matrices in machine learning models, like neural networks!

In [13]:
# Array of zeros
zeros = np.zeros((2, 3))  # 2 rows, 3 columns
print("Zeros:\n", zeros)

# Array of ones
ones = np.ones(12)  # One row array with 12 data
print("Ones:\n", ones)

# Array with a range
range_arr = np.arange(0, 10, 2)  # Start at 0, stop before 10, step by 2
print("Range:\n", range_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Range:
 [0 2 4 6 8]


# Step 2: Basic Operations
- NumPy makes math with arrays simple and fast.
- Unlike Python lists, NumPy applies operations to every element at once—no loops needed!

In [15]:
arr = np.array([1, 2, 3, 4])

# Add, subtract, multiply, divide to each element of an array by a number
print("Add 5:", arr + 5)      # [6, 7, 8, 9]
print("Multiply by 2:", arr * 2)  # [2, 4, 6, 8]

# Element-wise (with same size ans shape) operations between arrays
arr2 = np.array([5, 6, 7, 8])
print("Add arrays:", arr + arr2)  # [6, 8, 10, 12]

Add 5: [6 7 8 9]
Multiply by 2: [2 4 6 8]
Add arrays: [ 6  8 10 12]


In [42]:
# Create a 1D array from a Python list
temperatures = [25, 28, 30, 22, 19]
numpy_temps = np.array(temperatures)

# Convert Celsius to Fahrenheit in one line!
fahrenheit_temps = numpy_temps * 9/5 + 32

print("Celsius:", numpy_temps)
print("Fahrenheit:", fahrenheit_temps)

Celsius: [25 28 30 22 19]
Fahrenheit: [77.  82.4 86.  71.6 66.2]


# Step 3: Multi-Dimensional Arrays

### Concept:
- Real-world data is rarely 1D (e.g., images are 2D grids, videos are 3D).
- NumPy handles n-dimensional arrays effortlessly.

In [7]:
# Create a 2D array (rows = cities, columns = months)
monthly_temps = np.array([
    [25, 28, 30],  # City A (Jan, Feb, Mar)
    [18, 22, 20],  # City B
    [12, 15, 14]   # City C
])

print("2D Array of temp of three cities:\n", monthly_temps)

2D Array of temp of three cities:
 [[25 28 30]
 [18 22 20]
 [12 15 14]]


In [11]:
# Calculate average temperature for each city (use axis=1 to calcute the value in each row)
avg_monthly_temps = np.mean(monthly_temps, axis=1)
print("Average temps per city: ", avg_monthly_temps)

Average temps per city:  [27.66666667 20.         13.66666667]


In [21]:
# Maximum temp in each cities
np.max(monthly_temps, axis=1)

array([30, 22, 15])

In [27]:
# Find the hottest month across all cities
np.argmax(monthly_temps)  # output: 2 (index 2 referes to: City A, Mar)

2

In [28]:
monthly_temps_2 = np.array([
    [25, 28, 30],  # City A (Jan, Feb, Mar)
    [18, 32, 20],  # City B
    [12, 15, 14]   # City C
])
# Find the hottest month across all cities
np.argmax(monthly_temps_2)  # output: 4 (index 4 referes to: City B, Feb)

4

# Hands-On Exercises:

- Exercise 1: Create a 1-D array of 15 random integers between 0 and 100.
  > Hint: Use `np.random.randint(0, 101, size=15)`.
- Exercise 2: Reshape the array from Exercise 1 into a 3x5 matrix and print its shape.
- Exercise 3: Compute the sum, mean, and standard deviation of your 3x5 matrix.

In [40]:
# Creating a 1-D array of 15 radom data from 0 to 100
rand_int = np.array([
    np.random.randint(0, 101, size=15)
])

print("Random 1-D array:", rand_int)
print("Random 1-D array size:", rand_int.size, "and shape: ", rand_int.shape)

# Recreating the same array as a 2-D shape of 3x5 matrix
rand_int = rand_int.reshape((3, 5))
print("Reshaped random 1-D array:", rand_int)
print("Reshaped random 1-D array size:", rand_int.size, "and shape: ", rand_int.shape)

# Calculating sum, average, standard daviations of that data
row_sums = np.sum(rand_int, axis=1)
total_sum = np.sum(rand_int)
print("Row Sums:", row_sums)
print("Total Sum:", total_sum)

row_avg = np.mean(rand_int, axis=1)
total_avg = np.mean(rand_int)
print("Row Avg:", row_avg)
print("Total Avg:", total_avg)

row_sd = np.std(rand_int, axis=1)
total_sd = np.std(rand_int)
print("Row SD:", row_sd)
print("Total SD:", total_sd)

Random 1-D array: [[ 1 79 20 25 72 68 48 73 83 66 69 94 75 58 77]]
Random 1-D array size: 15 and shape:  (1, 15)
Reshaped random 1-D array: [[ 1 79 20 25 72]
 [68 48 73 83 66]
 [69 94 75 58 77]]
Reshaped random 1-D array size: 15 and shape:  (3, 5)
Row Sums: [197 338 373]
Total Sum: 908
Row Avg: [39.4 67.6 74.6]
Total Avg: 60.53333333333333
Row SD: [30.62417346 11.42978565 11.7405281 ]
Total SD: 25.171059219314195


# Exercise:
1. Create a 2D array for student scores (3 students, 5 subjects).
2. Calculate each student’s average score.
3. Find the subject with the highest total score across all students.

In [12]:
# Creating scores of three students (row-wise) in five subjects (column-wise)
student_scores = np.array([
    [10, 32, 31, 54, 64],  # Student 1: 5 subjects
    [53, 46, 75, 36, 86],  # Student 2: 5 subjects
    [75, 37, 36, 85, 58]   # Student 3: 5 subjects
])
print("3 Students' Scores in 5 Subjects (row: students, col: subjects) are:\n", student_scores)

# Calculating each student's average scroes
avg_scores = np.mean(student_scores, axis=1)
print("Average scores of each students:", avg_scores)  # Student 1: 38.2, Student 2: 59.2, Student 3: 58.2

# Calculating highest scorring subject for each student
highest_scores = np.argmax(student_scores, axis=1)
print("Subjects with highest score for each student (0-based index):", highest_scores)
# Student 1: 5th Subject, Student 2: 5th Subject, Student 3: 4th Subject

3 Students' Scores in 5 Subjects (row: students, col: subjects) are:
 [[10 32 31 54 64]
 [53 46 75 36 86]
 [75 37 36 85 58]]
Average scores of each students: [38.2 59.2 58.2]
Subjects with highest score for each students: [4 4 3]


# Real-World Mini-Project: Analyze Sports Data
## Task:
You’re a data analyst for a football team. The coach wants to know:
1. Which player has the most consistent performance (lowest standard deviation in goals per match)?
2. What’s the total goals scored in the last 5 matches?

## Date:
```python
goals = np.array([
    [2, 0, 1, 3, 2],  # Player 1
    [1, 1, 0, 2, 1],  # Player 2
    [3, 2, 2, 0, 4]   # Player 3
])
```
## Hints:
- Use `np.std()` for standard deviation.
- Use slicing `([:, -5:])` to get the last 5 matches.

In [11]:
# Given data of Goals for three football players
goals = np.array([
    [2, 0, 1, 3, 2],  # Player 1
    [1, 1, 0, 2, 1],  # Player 2
    [3, 2, 2, 0, 4]   # Player 3
])

# Add Assertions: Validate inputs (to ensure 5 matches).
assert goals.shape[1] == 5

# Finding the most consistent player (who has the lowest value) with Standard Deviation
# IDEA: the less the value of SD, the more the player has consistant performance
player_sds = np.std(goals, axis=1)
print("Standard Deviations of goals for each palyer:", player_sds)
# Finding the minimum SD value by considering lowest_sd as a 1-D array.
most_consistent_player = np.argmin(player_sds) + 1  # +1 used to make it Non-Zero based index (1, 2, 3... instead of 0, 1, 2, ...)
print(f"Player with most consistent performances is Player {most_consistent_player} as of his least SD value.")

# Finding the total goals scored in the last 5 matches
total_goals_in_last_5_matches = np.sum(goals[:, -5:])
print("Total goals scored in the last five matches are:", total_goals_in_last_5_matches)

Standard Deviations of goals for each palyer: [1.0198039  0.63245553 1.32664992]
Player with most consistent performances is Player 2 as of his least SD value.
Total goals scored in the last five matches are: 24


# Key Takeaways for NumPy
- **Vectorization**: Always prefer array operations over loops (faster and cleaner).
- **Axis Understanding**:
    - `axis=1` = row-wise operations.
    - `axis=0` = col-wise operations.
- **Edge Cases**: Some methods returns only the first occurance (if multiple exist) e.g., `np.argmax()`
    - *Solutions:*
        1. **Find All Indices** with `np.where()` where the value equals the maximum:
           ```python
           scores = np.array([90, 90, 85, 90, 75])
           max_val = scores.max()
           all_max_indices = np.where(scores == max_val)[0]  # Output: [0, 1, 3]
           ```
        2. **Random Selection** randomly pick from `all_max_indices`:
           ```python
           np.random.choice(all_max_indices)  # Could return 0, 1, or 3
           ```
        3. **Weighted Preference** for tie-breaking, apply custom logic (e.g., prioritize later indices):
           ```python
           last_max_index = all_max_indices[-1]  # Output: 3
           ```
    - *Real-World Application:*
    In recommendation systems, if two movies have the same rating, you might want to show both or prioritize the newer one.

# Step 4: Advanced NumPy Operations
Let’s level up with reshaping and broadcasting—key skills for handling real-world data like images, time series, or sensor data!

## Topic 1: Reshaping & Slicing Arrays

1. Why Learn This?
    - Data often needs restructuring (e.g., converting a 1D sensor stream into a 2D time-series matrix).
2. Concept:
    - Use `.reshape()` to change array dimensions without altering data.
    - Total elements must match (3x4 matrix = 12 elements).

In [18]:
# Convert 1D daily temperatures to a 2D weekly grid:
daily_temps = np.array([25, 26, 24, 23, 27, 28, 29, 30, 29, 28, 27, 26])
weekly_temps = daily_temps.reshape(3, 4)  # 3 weeks, 4 days each
print("2D weekly (3 weeks with 4 days each) temperature data:\n", weekly_temps)

2D weekly (3 weeks with 4 days each) temperature data:
 [[25 26 24 23]
 [27 28 29 30]
 [29 28 27 26]]


In [44]:
random_array = np.arange(10, 99, 2).reshape(5, 9)
print("Original 5x9 matrix 2Darray:\n", random_array)

print('-' * 30)

# Indexing and Slicing to work with a part of the whole data like [n:n, m:m] n=row index; m=col index
print("\nSliced - only the 3rd row:\n", random_array[2])
print("\nSliced - only 3rd column:\n", random_array[:, 2])
print("\nSliced - only the value from the 3rd row and the 3rd column:", random_array[2, 2])

print("\nSliced - from 4th row to the last:\n", random_array[3:])
print("\nSliced - from 4th column to the last:\n", random_array[:, 3:])
print("\nSliced - from 4th row & 4th column to the last:\n", random_array[3:, 3:])

print("\nSliced - upto the 3rd row:\n", random_array[:3])
print("\nSliced - upto the 3rd column:\n", random_array[:, :3])
print("\nSliced - upto the 3rd row and 3rd column:\n", random_array[:3, :3])

print("\nSliced - from 2nd to 4th row:\n", random_array[1:4])
print("\nSliced - from 2nd to 4th column:\n", random_array[:, 1:4])
print("\nSliced - from 2nd row & 2nd column to 4th row & 4th column:\n", random_array[1:4, 1:4])

print("\nSliced - the last three columns from the first two rows:\n", random_array[:2, -3:])

# Slicing extracts ranges using [start:stop:step]
print("\nSliced - every second element (for 1D array) or row (for 2D array):\n", random_array[::2])

# Boolean indexing (while a condition returns True)
print("\nExtracted - all elements > 50 into a single 1D array:", random_array[random_array > 50])

Original 5x9 matrix 2Darray:
 [[10 12 14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40 42 44]
 [46 48 50 52 54 56 58 60 62]
 [64 66 68 70 72 74 76 78 80]
 [82 84 86 88 90 92 94 96 98]]
------------------------------

Sliced - only the 3rd row:
 [46 48 50 52 54 56 58 60 62]

Sliced - only 3rd column:
 [14 32 50 68 86]

Sliced - only the value from the 3rd row and the 3rd column: 50

Sliced - from 4th row to the last:
 [[64 66 68 70 72 74 76 78 80]
 [82 84 86 88 90 92 94 96 98]]

Sliced - from 4th column to the last:
 [[16 18 20 22 24 26]
 [34 36 38 40 42 44]
 [52 54 56 58 60 62]
 [70 72 74 76 78 80]
 [88 90 92 94 96 98]]

Sliced - from 4th row & 4th column to the last:
 [[70 72 74 76 78 80]
 [88 90 92 94 96 98]]

Sliced - upto the 3rd row:
 [[10 12 14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40 42 44]
 [46 48 50 52 54 56 58 60 62]]

Sliced - upto the 3rd column:
 [[10 12 14]
 [28 30 32]
 [46 48 50]
 [64 66 68]
 [82 84 86]]

Sliced - upto the 3rd row and 3rd column:
 [[10 12 14]
 [28 30 32]
 [

In [39]:
# Get all elements from an array with conditions
temp_array = np.array(np.arange(9))
print("1D array:", temp_array)

# Filtering out the data/elements in the previous array
array_mask = temp_array >= 5
print("The elements of that array which are greater than or equal to 5:", temp_array[array_mask])

1D array: [0 1 2 3 4 5 6 7 8]
The elements of that array which are greater than or equal to 5: [5 6 7 8]


### Exercise:
Reshape this 1D array into a 3x3 matrix:
```python
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
```

In [22]:
# 1D Given data
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Convertes 1D into a 3x3 2D data matrix
reshaped_data = data.reshape(3, 3)
print(f"Converted this 1D given array:\n{data}\n\ninto a 2D data of 3x3 matrix:\n{reshaped_data}")

Converted this 1D given array:
[10 20 30 40 50 60 70 80 90]

into a 2D data of 3x3 matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


### Exercises
Run these in Jupyter Notebook and share your solutions—I’ll review them!

1. **Exercise 1**: Create a 1D array `[5, 10, 15, 20, 25, 30]`:
    - Print the second element.
    - Print the last two elements using slicing.
2. **Exercise 2**: Create a 3x3 array `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`:
    - Print the element at row 2, column 1.
    - Print the first two rows and last two columns.
3. **Exercise 3**: From the array `[12, 7, 19, 3, 15, 9]`:
    - Print values greater than 10 using boolean indexing.

In [59]:
# Exercise 1:
arr_1 = np.array([5, 10, 15, 20, 25, 30])
print("The second element of [5, 10, 15, 20, 25, 30] is:", arr_1[1])
print("The last two elements of [5, 10, 15, 20, 25, 30] are:", arr_1[-2:])

# Exercise 2:
arr_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The element at row 2, column 1 in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is:", arr_2[2, 1])
print("The first two rows in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:\n", arr_2[:2])
print("The last two columns in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:\n", arr_2[:, -2:])
print("The elements of first two rows and last two columns in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:\n", arr_2[:2, -2:])

# Exercise 3:
arr_3 = np.array([12, 7, 19, 3, 15, 9])
print("The values greater than 10 from the array [12, 7, 19, 3, 15, 9] are:", arr_3[arr_3 > 10])

The second element of [5, 10, 15, 20, 25, 30] is: 10
The last two elements of [5, 10, 15, 20, 25, 30] are: [25 30]
The element at row 2, column 1 in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is: 8
The first two rows in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:
 [[1 2 3]
 [4 5 6]]
The last two columns in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:
 [[2 3]
 [5 6]
 [8 9]]
The elements of first two rows and last two columns in the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] are:
 [[2 3]
 [5 6]]
The values greater than 10 from the array [12, 7, 19, 3, 15, 9] are: [12 19 15]


### Mini-Project: Sales Data Analysis

#### Task: You’re analyzing weekly sales data for a store.
Create a 2D array representing sales (in thousands) for 3 stores over 4 weeks:
```
[[10, 15, 12, 18],
 [20, 22, 19, 25],
 [14, 13, 17, 16]]
```
- **Part 1:** Print sales for the second week (column 1).
- **Part 2:** Print sales for all stores where sales exceed 15 thousand (use boolean indexing).
- **Part 3:** Print the total sales for each store (hint: use np.sum() with axis=1).

In [61]:
# Creating a 2D array representing sales (in thousands) for 3 stores over 4 weeks:
sales_in_thousands = np.array([
    [10, 15, 12, 18],  # Store 1: 4 weeks
    [20, 22, 19, 25],  # Store 2: 4 weeks
    [14, 13, 17, 16]   # Store 3: 4 weeks
])

print("Sales for the second week (column 1) for each store (in thousands):", sales_in_thousands[:, 1])
print("Sales for all stores exceed 15 thousand are:", sales_in_thousands[sales_in_thousands > 15])
print("Total sales (in thousands) for each stores are:", np.sum(sales_in_thousands, axis=1))

Sales for the second week (column 1) for each store (in thousands): [15 22 13]
Sales for all stores exceed 15 thousand are: [18 20 22 19 25 17 16]
Total sales (in thousands) for each stores are: [55 86 60]


## Topic 2: Broadcasting
- Why Learn This?
    - Perform operations on arrays of different shapes (e.g., scaling image pixels).
- Concept:
    - NumPy "stretches" smaller arrays to match larger ones without copying data.
    - Rules: Dimensions must be compatible (either same size or one is 1).

In [3]:
# Subtract the mean from each row of a matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

row_means = matrix.mean(axis=1, keepdims=True)  # [[2], [5]]
print("Means of each rows:\n", row_means)
centered_matrix = matrix - row_means  # Broadcasting subtracts 2 from row 1, 5 from row 2
print("Broadcasted subtract results for each rows:\n", centered_matrix)

Means of each rows:
 [[2.]
 [5.]]
Broadcasted subtract results for each rows:
 [[-1.  0.  1.]
 [-1.  0.  1.]]


### Exercise:
Multiply a 3x1 array by a 1x3 array using broadcasting:
```python
a = np.array([[1], [2], [3]])  # Shape (3,1)
b = np.array([4, 5, 6])        # Shape (3,)
```

In [46]:
# A 3x1 array (3 row and 1 column)
a = np.array([[1], [2], [3]])  # Shape (3,1)

# A 1x3 array (1 row and 3 columns)
b = np.array([4, 5, 6])  # Shape (1, 3)
# A 3x1 array (3 rows and 1 column) by explicitely defining "[:, np.newaxis]"
b2 = np.array([4, 5, 6])[:, np.newaxis]  # Shape (3, 1)

# Broadcasting multiplication of each row of 'a' array with the each column value of 'b' array
multiplied_array = a * b  # Makes a 3x3 multiplied matrix
# Altered behavvior in this case:
multiplied_array2 = a * b2  # Makes a 3x1 multiplied matrix

print("Multiplied 3x1 array by 1x3 array using broadcasting resultig a 3x3 matrix:\n", multiplied_array)
print("Multiplied 3x1 array by 3x1 array using broadcasting resultig a 3x1 matrix:\n", multiplied_array2)

Multiplied 3x1 array by 1x3 array using broadcasting resultig a 3x3 matrix:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Multiplied 3x1 array by 3x1 array using broadcasting resultig a 3x1 matrix:
 [[ 4]
 [10]
 [18]]


# Hands-On Exercises:
- Exercise 4: Create a 5x5 matrix of values from 0 to 24.
    - Extract a 3x3 submatrix from the center.
- Exercise 5: Using boolean masking, replace all elements in the 5x5 matrix that are divisible by 3 with -1.
- Exercise 6: Demonstrate broadcasting by multiplying each row of your matrix by a different scalar (e.g., [1, 2, 3, 4, 5]).

In [67]:
five_five_matrix = np.arange(0, 25).reshape(5, 5)
print("A 5x5 matrix from 0 to 24:\n", five_five_matrix)

# Detecting the center through calculating mean
extracted_matrix = five_five_matrix[2:, 2:]
print("3x3 matrix extracted from the 5x5 matrix:\n", extracted_matrix)

# Getting all the elements from the 5x5 matrix which are divisible by 3
divisible_mask = five_five_matrix % 3 == 0
# Replacing the matches with '-1' in the 5x5 matrix
five_five_matrix[divisible_mask] = -1
print("Replaced all elements in the 5x5 matrix that are divisible by 3 with -1:\n", five_five_matrix)

# Creating a 1x5 matrix different scalar
different_scalar = np.array([1, 2, 3, 4, 5])
# Broadcasting multiplication of 5x5 matrix by the 1x5 scalar matrix 
multiplied_matrix = five_five_matrix * different_scalar
print("Multiplied the 5x5 matrix with the new 1x5 scalar matrix using broadcasting:\n", multiplied_matrix)

A 5x5 matrix from 0 to 24:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
3x3 matrix extracted from the 5x5 matrix:
 [[12 13 14]
 [17 18 19]
 [22 23 24]]
Replaced all elements in the 5x5 matrix that are divisible by 3 with -1:
 [[-1  1  2 -1  4]
 [ 5 -1  7  8 -1]
 [10 11 -1 13 14]
 [-1 16 17 -1 19]
 [20 -1 22 23 -1]]
Multiplied the 5x5 matrix with the new 1x5 scalar matrix using broadcasting:
 [[-1  2  6 -4 20]
 [ 5 -2 21 32 -5]
 [10 22 -3 52 70]
 [-1 32 51 -4 95]
 [20 -2 66 92 -5]]


# Mini-Project: Sensor Data Analysis

## Scenario:
You’re analyzing data from a wearable fitness tracker. The raw data is a 1D array of heart rates (beats per minute) recorded every minute for 24 hours (1440 values).

## Tasks:
1. Reshape the data into a 24x60 matrix (rows = hours, columns = minutes).
2. Calculate the average heart rate per hour.
3. Normalize each hour’s data by subtracting its mean.

## Sample Data:
```python
heart_rates = np.random.randint(60, 100, size=1440)  # Simulated data
```

## Hints:
- Use `reshape(24, 60)`.
- Use `axis=1` for row-wise operations.

In [47]:
# Heart rate (BMP) data from a wearable fitness tracker for 24 Hrs. recorded every minutes
heart_rates = np.random.randint(60, 100, size=1440)  # Simulated data
heart_rates_per_hour = heart_rates.reshape(24, 60)  # Making the data into hours (row) and minutes (column) format

# Calculating the average heart rate per hour (to maintain shape for broadcasting 'keepdims=True' is used)
avg_heart_rate_per_hour = np.mean(heart_rates_per_hour, axis=1, keepdims=True)
print("Average heart rate per hour are:\n", avg_heart_rate_per_hour)

# Normalizing each hour's data by subtracting its mean
normalized_heart_rates_per_hour = heart_rates_per_hour - avg_heart_rate_per_hour
print("Normalized heart rates per hour:\n", normalized_heart_rates_per_hour)

Average heart rate per hour are:
 [[81.11666667]
 [77.08333333]
 [79.7       ]
 [79.53333333]
 [80.08333333]
 [79.25      ]
 [77.2       ]
 [79.71666667]
 [80.38333333]
 [81.26666667]
 [79.5       ]
 [79.11666667]
 [79.55      ]
 [78.46666667]
 [78.01666667]
 [80.01666667]
 [77.28333333]
 [81.61666667]
 [77.4       ]
 [79.13333333]
 [78.5       ]
 [79.81666667]
 [80.36666667]
 [80.43333333]]
Normalized heart rates per hour:
 [[  5.88333333 -11.11666667  10.88333333 ...  14.88333333  -0.11666667
  -16.11666667]
 [ -6.08333333 -11.08333333  18.91666667 ...  -2.08333333   4.91666667
   -9.08333333]
 [-10.7         -4.7         18.3        ...  -2.7         -7.7
    9.3       ]
 ...
 [ 14.18333333  -0.81666667   6.18333333 ...   9.18333333 -18.81666667
  -14.81666667]
 [  6.63333333 -10.36666667  -1.36666667 ...  15.63333333   5.63333333
   -6.36666667]
 [  9.56666667 -19.43333333  16.56666667 ...   0.56666667  11.56666667
    8.56666667]]


# Exercises
Try these in Jupyter Notebook to practice what you’ve learned. I’ll provide solutions after you give them a shot!
1. **Exercise 1**: Create a 3x3 array filled with the number 7. Print it.
2. **Exercise 2**: Make an array with numbers from 10 to 20 (inclusive) with a step of 2. Multiply it by 3 and print the result.
3. **Exercise 3**: Create two 2x2 arrays:
    - One with values `[[1, 2], [3, 4]]`.
    - Another with values `[[5, 6], [7, 8]]`.
    - Add them together and print the result.

In [52]:
# Exercise 1:
# Way 2 -
# Making an empty array later filled with 7
# sevens_array = np.empty((3, 3))
# sevens_array.fill(7)
# Way 1 - (Preferable)
# Use 'np.full()' method to avoid the extra step above
sevens_array = np.full((3, 3), 7)
print("A 3x3 array filled with 7:\n", sevens_array)

# Exercise 2:
# Making an array from 10 to 20 with a step of 2
number_array = np.arange(10, 21, 2)
multiplied_array = number_array * 3  # Multiplied each numbers of that array by 3
print("An array with numbers from 10 to 20 with a step of 2:", number_array)
print("Multiplied the array with 3:", multiplied_array)

# Exercise 3:
# Creating two 2x2 arrays
array_one = np.array([[1, 2], [3, 4]])
array_two = np.array([[5, 6], [7, 8]])
array_sum = array_one + array_two
print("Sum of the two arrays:\n", array_sum)

A 3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
An array with numbers from 10 to 20 with a step of 2: [10 12 14 16 18 20]
Multiplied the array with 3: [30 36 42 48 54 60]
Sum of the two arrays:
 [[ 6  8]
 [10 12]]


# Mini-Project: Temperature Conversion
## Task:
You’re a data analyst converting a week’s temperature data from Celsius to Fahrenheit.

- Create a NumPy array with these Celsius temps: `[25, 28, 22, 30, 27, 26, 24]`.
- Convert to Fahrenheit using the formula: `F=C×9/5+32`.
- Print the original and converted arrays.

## Hint:
Use broadcasting to apply the formula across the entire array in one line!

In [63]:
# Creating an array with given temperature data
temperature_celsius = np.array([25, 28, 22, 30, 27, 26, 24])

# Converting Celsius data into Fahrenheit using broadcasting
temperature_fahrenheit = temperature_celsius * 9/5 + 32
print("Temperature data in Celsius:", temperature_celsius)
print("Converted temperature data in Fahrenheit using broadcasting:", temperature_fahrenheit)
print("Converted temperature data in Fahrenheit using broadcasting (rounded to one decimal):", np.round(temperature_fahrenheit, decimals=1))

Temperature data in Celsius: [25 28 22 30 27 26 24]
Converted temperature data in Fahrenheit using broadcasting: [77.  82.4 71.6 86.  80.6 78.8 75.2]
Converted temperature data in Fahrenheit using broadcasting (rounded to one decimal): [77.  82.4 71.6 86.  80.6 78.8 75.2]


## Topic 3: NumPy Random Module
Let’s explore random number generation—essential for simulations, data augmentation, and testing.

### Random Sampling:
- Generate random integers, floats, or samples from distributions.
- Example: Simulate dice rolls:

In [65]:
dice_rolls = np.random.randint(1, 7, size=10)  # 10 rolls of a 6-sided die
print(dice_rolls)

[6 6 1 4 4 2 6 3 2 5]


### Seeding for Reproducibility:
- Use `np.random.seed()` to ensure the same random numbers are generated every time.

In [86]:
np.random.seed(42)
print(np.random.rand(3))  # Always the same output

[0.37454012 0.95071431 0.73199394]


### Distributions:
- Generate data from normal, uniform, or exponential distributions.
- Example: Simulate heights of 100 people (normal distribution):

In [87]:
heights = np.random.normal(loc=170, scale=10, size=100)  # Mean=170cm, Std=10cm
print(heights)

[158.88119882 173.18902185 172.79041292 180.10515285 164.19121866
 164.74830193 164.28619834 160.75917162 143.87450987 179.50369682
 178.16445081 154.76124002 165.71953936 162.57593163 162.96656198
 148.60379344 163.70525039 175.97720467 195.59488031 173.94233022
 171.22219165 164.84564338 163.9974615  179.47439821 172.91034001
 163.6444026  159.78447805 168.38244614 164.66351196 169.94472138
 167.70549546 173.89348913 157.34880886 180.91992264 197.78313042
 181.93639724 172.18638316 178.81761039 159.90914657 154.16705786
 177.73700417 164.61858338 156.53321903 161.19408734 158.69447695
 171.34428883 175.82122795 178.8774846  178.9433233  177.54997797
 167.9283411  163.76522605 154.9184671  180.99646976 168.22267879
 165.89616691 181.79716345 161.01792061 178.34795419 172.96561384
 159.62170123 169.24196255 179.72963534 177.95595464 184.95434253
 173.38181252 203.72296254 160.79609195 166.0136161  169.39135913
 155.81249541 180.42491617 179.03532491 170.19000331 164.65583546
 155.04946

#### Exercise:
- Simulate 1000 coin flips and calculate the probability of getting heads.

In [40]:
# Simulating 1000 coin flips using 0s and 1s
coin_flips = np.random.randint(0, 2, size=1000)

# Calculating the total number of heads
# Assuming: 0 = tails, 1 = heads
# Use 'np.sum()' if the values are only 0s and 1s to get the total number of 1s as their sum, otherwise
# ...use the below method to get the count of a particular value in an NumPy array
total_heads = coin_flips[coin_flips == 1].size

# Calculating the pronanlity of getting heads
# Formula: Probablity = Total Number of Heads / Total Number of Flips
heads_probablity = (total_heads / 1000) * 100  # Multiplied by 100 to get the percentage value

print(f"Probablity of getting heads from a 1000 flips of a coin is: {heads_probablity:.1f}%")

Probablity of getting heads from 1000 flips of a coin is: 48.7%


In [ ]:
Dear Sir/Madam,
I am writing to report a UPI transaction issue that occurred on [DATE] at approximately [TIME]. I made a payment of Rs. [AMOUNT] to [MERCHANT NAME] (Medicine Shop) using the YONO SBI application by scanning their POS terminal QR code.

**Transaction Details:**
- UPI Transaction ID: [YOUR TRANSACTION ID]
- Date & Time: [DATE & TIME]
- Amount: Rs. [AMOUNT]
- Merchant: [MEDICINE SHOP NAME]
- Payment Mode: UPI via YONO SBI application

**Issue Description:**
While my YONO SBI application displayed a "Transaction Completed" success message and the amount was debited from my account, the merchant's POS terminal showed "Session Expired" and did not register the payment as successful. I have verified through both the YONO SBI application and my SBI Internet Banking statement that the amount has been deducted from my account. Even after 24+ hours, the amount has neither been credited to the merchant nor returned to my account.

I have already discussed this issue with the merchant, who advised me to contact SBI Bank to resolve this matter.

I request your immediate investigation into this transaction and appropriate action to either:
1. Credit the payment to the merchant's account, OR
2. Refund the amount to my bank account

I have retained all evidence of this transaction, including screenshots and bank statements, which I can provide if required.

Given the essential nature of my purchase (medicine), I would appreciate your prompt attention to this matter.

Thank you for your assistance.

Sincerely,
[YOUR FULL NAME]
[YOUR ACCOUNT NUMBER]
[YOUR REGISTERED MOBILE NUMBER]
[YOUR EMAIL ADDRESS]